"""Train a reproducible, real TF-IDF + logistic-regression baseline.

Input CSV columns: Review,Label. Labels are preserved from the supplied dataset.
No data is bundled or generated by this script.
"""

import argparse
import csv
import hashlib
from datetime import datetime, timezone
from pathlib import Path

import joblib
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, f1_score
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline

SUPPORTED_LABELS = {"positive", "negative", "neutral"}

def read_dataset(path: Path) -> tuple[list[str], list[str]]:
    texts, labels = [], []
    with path.open("r", encoding="utf-8-sig", newline="") as handle:
        reader = csv.DictReader(handle)
        required = {"Review", "Label"}
        if not reader.fieldnames or not required.issubset(reader.fieldnames):
            raise ValueError("Dataset must contain required columns: Review and Label.")
        seen: set[str] = set()
        for line_number, row in enumerate(reader, start=2):
            text = (row.get("Review") or "").strip()
            label = (row.get("Label") or "").strip().casefold()
            if not text or not label:
                raise ValueError(f"Row {line_number} has an empty Review or Label.")
            if label not in SUPPORTED_LABELS:
                raise ValueError(
                    f"Row {line_number} has unsupported Label {label!r}; "
                    "use Positive, Negative, or Neutral."
                )
            normalized = " ".join(text.casefold().split())
            if normalized in seen:
                raise ValueError(f"Duplicate Review found at row {line_number}; remove duplicates before training.")
            seen.add(normalized)
            texts.append(text)
            labels.append(label)
    if len(texts) < 6 or len(set(labels)) < 2:
        raise ValueError("Dataset needs at least 6 non-empty rows and two distinct labels.")
    return texts, labels


def train(input_path: Path, output_path: Path) -> dict:
    texts, labels = read_dataset(input_path)
    test_rows = max(1, round(len(texts) * 0.2))
    stratify = labels if (
        min(labels.count(label) for label in set(labels)) >= 2
        and test_rows >= len(set(labels))
    ) else None
    x_train, x_test, y_train, y_test = train_test_split(
        texts, labels, test_size=0.2, random_state=42, stratify=stratify
    )
    pipeline = Pipeline(
        [
            ("tfidf", TfidfVectorizer(lowercase=True, ngram_range=(1, 2), min_df=1)),
            ("classifier", LogisticRegression(max_iter=1000, random_state=42)),
        ]
    )
    pipeline.fit(x_train, y_train)
    predictions = pipeline.predict(x_test)
    metrics = {
        "accuracy": accuracy_score(y_test, predictions),
        "macro_f1": f1_score(y_test, predictions, average="macro", zero_division=0),
        "classification_report": classification_report(
            y_test, predictions, labels=sorted(set(labels)), zero_division=0, output_dict=True
        ),
        "train_rows": len(x_train),
        "test_rows": len(x_test),
    }
    dataset_checksum = hashlib.sha256(input_path.read_bytes()).hexdigest()
    artifact = {
        "pipeline": pipeline,
        "metadata": {
            "model_version": f"baseline-{datetime.now(timezone.utc).strftime('%Y%m%d%H%M%S')}",
            "labels": list(pipeline.classes_),
            "metrics": metrics,
            "dataset_checksum": dataset_checksum,
            "dataset_path": str(input_path.resolve()),
            "random_seed": 42,
            "input_columns": ["Review", "Label"],
        },
    }
    output_path.parent.mkdir(parents=True, exist_ok=True)
    joblib.dump(artifact, output_path)
    return metrics


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("input_csv", type=Path)
    parser.add_argument("--output", type=Path, default=Path("artifacts/baseline.joblib"))
    args = parser.parse_args()
    metrics = train(args.input_csv, args.output)
    print(f"Saved {args.output}")
    print(f"accuracy={metrics['accuracy']:.4f} macro_f1={metrics['macro_f1']:.4f}")


if __name__ == "__main__":
    main()
